### ISSUE TITLE
sintesis 

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-mel-16#1]
[sintesis 2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-mel-16/files/12704309/sintesis.2.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
